### ISSUE TITLE
Reproducible research

### ISSUE THREAD

**Issue by sbellem** [initc3/HoneyBadgerMPC#100]
_draft_

This is an issue to note down required details to ensure that experiments along with their results can be reproduced by others. For instance, even though the code may be open source and one may provide the commit hash of the code that was used to conduct an experiment this may not guarantee that the experiment will be reproducible if different versions of some dependencies are used.

To help making things clearer: THE CODE means everything that is captured by a commit hash.

Here's a tentative list of things THE CODE of an experiment should provide:

- [ ] `Pipfile` and `Pipfile.lock` (see https://pipenv.readthedocs.io/en/latest/basics/#pipenv-lock)
- [x] Dockerfile(s)

**Comment by amiller** [comment]
Here's a general concept to mention:
- when we do benchmarking, and read measurements from log file printouts (latency, bytes measured, etc.) we should make sure to save the raw files, commit them to a git repository of some kind
- we generally want to do analysis on a spreadsheet of just the most interesting results basically, so one of the steps is to by script (or by hand) parse the log file and copy out the relevant fields. However, we should not just delete the raw files we read, since otherwise we would waste an opportunity to catch or double check mistakes in transcription

**Comment by sbellem** [comment]
> * when we do benchmarking, and read measurements from log file printouts (latency, bytes measured, etc.) we should make sure to save the raw files, commit them to a git repository of some kind
> 
> * we generally want to do analysis on a spreadsheet of just the most interesting results basically, so one of the steps is to by script (or by hand) parse the log file and copy out the relevant fields. However, we should not just delete the raw files we read, since otherwise we would waste an opportunity to catch or double check mistakes in transcription

Just some thoughts (_copied from the discussion on Slack_):

## For now
What if after each run a script (python or shell) was run to simply push the log files to a dedicated github repo? The commit message could contain the commit hash of the code that produced the log files. That should be relatively easy and quick to setup. The files could be compressed and archived in a tar ball before being committed to save space if needed.

I think that could be a quick and fast first improvement.

## For the near future
In a second iteration, I would look into whether the logs are structured or not and if not would structure them using, one of:

1. https://www.structlog.org/
2. https://docs.python.org/3/howto/logging-cookbook.html#implementing-structured-logging

and would automate the parsing and start looking into persisting them to some kind of datastore that is good for that. Eventually this approach probably would start mimicking what the ELK stack provides ... 

## For the long term
Using something like the "ELK" stack (https://www.elastic.co/elk-stack) could perhaps be good but may require too much work to setup for now.

> "ELK" is the acronym for three open source projects: 
> * **Elasticsearch** is a search and analytics engine.
> * **Logstash** is a server‑side data processing pipeline that ingests data from multiple sources simultaneously, transforms it, and then sends it to a "stash" like Elasticsearch.
> * **Kibana** lets users visualize data with charts and graphs in Elasticsearch. 


## Brief summary
* **Iteration 1** First simply write a small function that can collect the log files and push them to a dedicated github repo. Run this function as needed, potentially after each benchmark run.
* **Iteration 2** Structure the logs using the library `structlog` (https://www.structlog.org/) or the approach documented in Python's docs: https://docs.python.org/3/howto/logging-cookbook.html#implementing-structured-logging -- this should open up the door to automating the parsing of the logs and thus help preventing errors from the extraction of the logged data.

---

## About `structlog`
From https://www.structlog.org/en/stable/processors.html#id3:
> The probably most useful formatter for string based loggers is [`JSONRenderer`](https://www.structlog.org/en/stable/api.html#structlog.processors.JSONRenderer). Advanced log aggregation and analysis tools like [logstash](https://www.elastic.co/products/logstash) offer features like telling them “this is JSON, deal with it” instead of fiddling with regular expressions.

For examples of `structlog` see https://www.structlog.org/en/stable/examples.html.

The following gives a very god and bried summary of the ELK stack is and how it can be used with `structlog`: https://www.structlog.org/en/stable/logging-best-practices.html

**Comment by amiller** [comment]
I'm leaving this open so we all think about it while completing the next round of benchmarking for publication.
Minimum requirements:
- Every benchmark log MUST come with github commit associated with it
- Store raw log files, somewhere, so we can review. Typically we mostly look at the overall timestamps recorded in an online spreadsheet, which is fine but not a replacement for storing the log files

**Comment by amiller** [comment]
Closing this as unspecific for now
