### ISSUE TITLE
Change passive.py to robust.py

### ISSUE THREAD

**Issue by amiller** [initc3/HoneyBadgerMPC#109]
This could be a sort of finicky change, so needs coordination.
In principle this is just cosmetic, but before we start doing benchmarking results whose setup we archive for reproducibility, this name should be changed to be accurately descriptive. 
(It would look suspicious if we run passive.py yet claim our results are for the robust case. In fact we've implemented the robust scheme, and this issue is just to put  the fileanme in sync with that)

**Comment by amiller** [comment]
To clarify - this needs to be expedited to prior to running our benchmarks

**Comment by smkuls** [comment]
This was fixed in #127
