### ISSUE TITLE
Change sid to something more unique than an integer

### ISSUE THREAD

**Issue by kev-liao** [initc3/HoneyBadgerMPC#116]
If two ProgramRunners are running concurrently then both will start with the same integer id and will end up clashing. Fix this by taking a prefix from the user to make it unique.

**Comment by smkuls** [comment]
This was actually opened by my.

**Comment by smkuls** [comment]
Looks like this was resolved. The `sid` is a key to a dictionary so both string and integers are supported. The user can provide either to distinguish the communication.
