### ISSUE TITLE
Interface C++ code with CFFI wrappers

### ISSUE THREAD

**Issue by smkuls** [initc3/HoneyBadgerMPC#117]
- [x] Port compute-power-sums to cffi instead of running using a shell command
- [x] As a part of this effort, try and eliminate all shell commands since this will provide a good performance benefit.
- [x] Also move polynomial interpolation to C++ and call using a CFFI wrapper.
- [x] Evaluate NTL vs flint also as a part of this.

**Comment by amiller** [comment]
@rahulgovind has hit this out of the park with #175 #160 etc
