### ISSUE TITLE
Bandwidth logging

### ISSUE THREAD

**Issue by amiller** [initc3/HoneyBadgerMPC#129]
Let's use `bwm-ng` to log bandwidth. I've investigated a handful of alternatives and this seems like the best for generating a time series of BW usage.  It's available as an ubuntu package:
`sudo apt-get install bwm-ng`

```
bwm-ng -o csv -t 1000 -I lo > bw-log-$(date +%s).txt
```

The format is:
```
unix timestamp
interface
bytes_out/s
bytes_in/s
bytes_total/s
```

Example output:
```
1541900576;lo;0.00;0.00;0.00;0;0;0.00;0.00;0.00;0;0;0.00;0.00;0;0
1541900576;total;0.00;0.00;0.00;0;0;0.00;0.00;0.00;0;0;0.00;0.00;0;0
1541900577;lo;9488300.00;9488300.00;18976600.00;9488300;9488300;983.00;983.00;1966.00;983;983;0.00;0.00;0;0
1541900577;total;9488300.00;9488300.00;18976600.00;9488300;9488300;983.00;983.00;1966.00;983;983;0.00;0.00;0;0
1541900578;lo;9221216.00;9221216.00;18442432.00;9221216;9221216;888.00;888.00;1776.00;888;888;0.00;0.00;0;0
1541900578;total;9221216.00;9221216.00;18442432.00;9221216;9221216;888.00;888.00;1776.00;888;888;0.00;0.00;0;0
```

This would be suitable for reconstructing a time series of how much bandwidth each phase of the protocol requires

**Comment by smkuls** [comment]
I am not sure if this would be a good way to go about this. We are using asyncio code and this way would be pretty non deterministic, we would have a hard time figuring out what was getting executed when the bandwidth utilization was high/low if that's the goal.

**Comment by amiller** [comment]
I was thinking it could be useful to have a graph that shows a time series of a run, where we annotated the different phases of the protocol, and show how they correspond to different resource bottelnecks. From the main log file, we'll have timestamps correpsonding to the main phase transitions

**Comment by smkuls** [comment]
That will be a lot of manual work and there's no easy way to automate it, we can do it for a few runs manually and see if the bandwidth usage is as expected but that's about it.

**Comment by amiller** [comment]
Fine leaving this issue closed to defer to later. I don't think automation should be too hard though.
