### ISSUE TITLE
Cleanup all .py files under honeybadgermpc directory

### ISSUE THREAD

**Issue by smkuls** [initc3/HoneyBadgerMPC#137]

**Comment by smkuls** [comment]
- [x] Remove dead branches from master

- [x] Change names to underscores

- [ ] Take a pass over cleaning up the code -> variable names / linting issues / prefix `sh` to shares and avoid statements like - `x = open(x)`

- [ ] Remove main

- [ ] Move apps and their tests to the same folder

**Comment by smkuls** [comment]
This is an iterative process and is being worked on in part with PRs which fix other issues.

**Comment by amiller** [comment]
Closing as this is largely factored out with progs etc
