### ISSUE TITLE
Fix terminology (butterfly => benes)

### ISSUE THREAD

**Issue by amiller** [initc3/HoneyBadgerMPC#142]
Our shuffling network is better described as a Benes network. It is equivalent to two butterfly networks back to back. The usual analysis of a Benes network is that it can exhibit all possible permutations, which is necessary but not sufficient for the property that we want, which is that all permutations are equally likely.
This paper gives a good summary. https://scholar.google.com/scholar?cluster=12997914050888668855

There are example examples in the literature of the use of Benes networks for mixing, which is the same property that we want. However, since it turns out that not all permutations are equally likely, we have to give some attention to this.

https://link.springer.com/content/pdf/10.1007/3-540-44586-2_23.pdf
"We show that randomly selecting each control signal results in a biased permutation even ifall servers behave correctly"

**Comment by smkuls** [comment]
We no longer need this, we have switched to an iterative butterfly network which performs multiple iterations of butterfly network.
