### ISSUE TITLE
wb_interpolate can't decode a message that is all zeros

### ISSUE THREAD

**Issue by amiller** [initc3/HoneyBadgerMPC#143]
This commit adds a test case for wb_interpolate that seems to indicate a bug. Usually when we've encountered this case, it's because of some other mistake (we usually aren't decoding all 0's). But there's nothing wrong with a sharing that is all 0's, it's the constant polynomial f(x) = 0 which should represent a value 0.

https://github.com/initc3/HoneyBadgerMPC/commit/20620fd69f97797d93908006abc5f21b350b4e65
https://github.com/initc3/HoneyBadgerMPC/tree/asyncmix-master-wbinterpolatefix

This test fails (TODO: update when travis finishes)
https://travis-ci.org/initc3/HoneyBadgerMPC/branches

The error in this case is something like:
```
File "/usr/src/HoneyBadgerMPC/honeybadgermpc/linearsolver.py", line 65, in isPivotColumn
    while A[i][j] == 0 and i < len(A):
IndexError: list index out of range
```

The problem seems to be that `wb_interpolate` fails to find a pivot point. Is this the only case where that can happen? Would a special check be sufficient?

**Comment by smkuls** [comment]
This does not happen with Gao's algorithm. I have asked @rahulgovind to write a test case for this for both Gao and `wb_interpolate` so that we keep track of this issue.

**Comment by amiller** [comment]
I think this is no longer an issue, I'm closing as all our batch decoding has been significantly changed and there are no outstanding problems
