### ISSUE TITLE
Improve performance of polynomial interpolation for large N

### ISSUE THREAD

**Issue by amiller** [initc3/HoneyBadgerMPC#152]
We have the raw materials to do FFT-based evaluation.
This does not matter much for small values of N, but at N=50 it makes a 10x or more difference, e.g. N^2 = 2500 vs N log2 N = ~250. The only challenge is we have to switch to using roots of unity everywhere when generating and reconstructing secret shared encodings.

**Comment by amiller** [comment]
Some work in progress on this is here, but there's no chance of it in time :(
https://github.com/amiller/HoneyBadgerMPC/tree/asyncmix-master-withfft

**Comment by amiller** [comment]
BTW I no longer think that FFT is feasible in general. When we are decoding from an arbitrary subset of `t+1` shares from nodes, and extrapolating to see if it coincides with the remaining `t` values, we cannot seem to use FFT for this because FFT will require exactly the points omega**i for i 0 thrhoguh n-1.

**Comment by amiller** [comment]
Here's a summary of the costs of interpolation right now:
basically the bottleneck looks like overhead in function calls to mul which should be much faster if this were in a c++ or rust routine
```
starting test1. k: 1000 n: 50 t: 16
Test n = 50, t = 16, field = 52435875175126190479447740508185965837690552500527637822603658699938581184513
         18039204 function calls (17998152 primitive calls) in 11.571 seconds

   Ordered by: cumulative time, internal time
   List reduced from 57 to 29 due to restriction <0.5>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.006    0.006   11.571   11.571 batch_reconstruction.py:75(attempt_reconstruct_batch)
      589    0.043    0.000   11.557    0.020 robust_reconstruction.py:15(attempt_reconstruct)
      589    0.007    0.000    9.532    0.016 wb_interpolate.py:129(decode)
      589    0.169    0.000    9.487    0.016 polynomial.py:83(interpolate)
    20526    0.666    0.000    4.324    0.000 polynomial.py:174(__mul__)
  2294424    2.591    0.000    3.969    0.000 field.py:129(__add__)
    20493    0.074    0.000    3.419    0.000 polynomial.py:169(__add__)
    20493    0.148    0.000    3.062    0.000 polynomial.py:170(<listcomp>)
   644712    0.471    0.000    2.928    0.000 {built-in method builtins.sum}
  1338447    1.568    0.000    2.646    0.000 field.py:175(__mul__)
  4358384    2.347    0.000    2.347    0.000 field.py:124(__init__)
    19437    0.333    0.000    1.922    0.000 polynomial.py:49(__call__)
    19437    0.515    0.000    1.677    0.000 polynomial.py:89(lagrange)
    20526    0.203    0.000    0.718    0.000 polynomial.py:178(<listcomp>)
    64957    0.357    0.000    0.615    0.000 polynomial.py:31(__init__)
   723335    0.273    0.000    0.576    0.000 field.py:103(__call__)
  1321716    0.392    0.000    0.533    0.000 field.py:317(__hash__)
  1358412    0.416    0.000    0.416    0.000 field.py:286(__eq__)
  3633927    0.413    0.000    0.413    0.000 {built-in method builtins.isinstance}
    64957    0.129    0.000    0.249    0.000 polynomial.py:9(strip_trailing_zeros)
       66    0.002    0.000    0.201    0.003 {built-in method _functools.reduce}
     2112    0.001    0.000    0.199    0.000 polynomial.py:94(mul)
  1321716    0.141    0.000    0.141    0.000 {built-in method builtins.hash}
    75983    0.106    0.000    0.106    0.000 field.py:295(__ne__)
320417/279365    0.045    0.000    0.060    0.000 {built-in method builtins.len}
    41052    0.033    0.000    0.058    0.000 polynomial.py:40(isZero)
   100518    0.034    0.000    0.055    0.000 polynomial.py:161(__iter__)
       33    0.002    0.000    0.034    0.001 polynomial.py:95(<listcomp>)
      589    0.006    0.000    0.031    0.000 wb_interpolate.py:140(<listcomp>)
```

**Comment by amiller** [comment]
Here is a potential alternative recipe for robust reconstruction. It may be useful for reducing the first phase of batch reconstruction, although it does not seem to improve the entire overall time per element to sublinear. The idea takes advantage of two facts: 
 1. Lagrange interpolation to recover *coefficients* of a polynomial is O(N^2), however lagrange interpolation and *evaluation* at a fixed point `a` is only O(N). Instead of the Lagrange polynomials as `p_i(X)`, we just directly take `p_i(a)` already evaluated at `a`.
 2. Consider two polynomials `F` and `G` of degree `2t`.  If `F != G`, then they must disagree at the vast majority of points (i.e. at `|Fp| - 2t` points, since otherwise they'd coincide at 2t+1 points and therefore be identical). This is the same rationale for polynomial check at a random location....

With these facts in mind, the recipe for robust reconstruction is the following:
- Wait for 2t+1 shares
- Consider the polynomial `F` defined by all 2t+1 shares. Evaluate `F(a)` for a randomly sampled `a`.
- Pick a subset of t+1 shares. Consider `G` defined by these, and evaluate `G(a)`. 
- Clearly `F` and `G` are both degree-bound `2t`, so if `F(a) = G(a)` we conclude `F = G` of degree `t`.
- If the check above passes, output `G(0)` as the recovered secret.

This gives robust reconstruction of a secret for only N operations. However, it does not give all the polynomial coefficients, which is what we need to return at the end of batch reconstruction.

**Comment by amiller** [comment]
This paper seems to provide an algorithm for polynomial interpolation of RS codes using FFT.
Soro and Lacan. FNT-based Reed-Solomon Erasure Codes
https://arxiv.org/pdf/0907.1788.pdf
Section II B

The solution is derived from lagrange interpolation. But the main idea is to take advantage of the fact that polynomial multiplication can be efficient using FFT to convert to point-form and carrying out the multiplication in point form. The result is a way of transforming the polynomial so that even given an arbitrary subset of polynomial evaluation points, the interpolation can be carried out using FFT operations.

**Comment by amiller** [comment]
I implemented the above approach in this commit: 
https://github.com/initc3/HoneyBadgerMPC/commit/1e540825cedf8e

It seems to work! Essentially the decomposition of the problem is into two parts. The first depends only on the points to evaluate (the IDs of the parties providing shares), and amounts to defining and evaluating an auxiliary polynomial `A(X)` that depends on these points. This takes `N^2` done naively, the paper says it can be reduced to `N log^2 N` but regardless this only needs to be done once for a batch. For each chunk of the batch, different `ys` values, the reconstruction consists of two iterations of FFT.

The first part is `fnt_decode_step1` (depends only on `xs` values), the second part `fnt_decode_step2` (depends on `ys` values) clearly takes `O(N log N)` time.

Still to do:
- [x] integrate this decoding method into the secret share decoding pipeline
- [x] implement this in C++ for efficiency using one of the number libraries (especially the `fnt_decode_step2` which would be called in a loop for all the chunks in a batch

**Comment by rahulgovind** [comment]
Overall, it seems that polynomial interpolation using Vandermonde matrices would be a better alternative to FFT-based interpolation or Lagrange interpolation for small n. 

Batch size is also a parameter that needs to be considered. Vandermonde-based interpolation uses matrix inversion which is an O(N^3) operation. However, the matrix inversion needs to be done only once for a batch and is therefore negligible for large batches. 

I ran some benchmarks to compare the interpolation time required for
- Pure python interpolation (which uses Langrange interpolation and is what we have been using till now)
- NTL interpolation (which also uses Lagrange interpolation underneath)
- Interpolation using Vandermonde matrices FNT decoding (which is written in Cython/C++) 
- Interpolation using FNT decoding (which is also written in Cython/C++)

For the benchmarks, I decoded `k/t` polynomials of degree `t-1`. k is effectively the batch size and is set to 4096 for the benchmarks. [Link to benchmark_interpolate.py](https://gist.github.com/rahulgovind/1ea0f824fac04d2284720497a9983e8b) The benchmarks were done using code from PR #176 (909ee41d5e56b9213edf01c5fc581df99ac0236c)

From the plots below, Vandermonde-based interpolation is faster than FNT decoding until approximately (t=64). So a good strategy is to use Vandermonde until t=64 and then FFT. Small batch sizes need to be explored further.
![Time/Speed up plots](https://i.imgur.com/kvlyq2I.png)

**Comment by amiller** [comment]
@rahulgovind Can you please edit the message above with some context, where did those graphs come from, if they're from running code point to the relevant git commit for versioning (and, also, please always upload a graph with an x axis / y axis label & units))

**Comment by rahulgovind** [comment]
> @rahulgovind Can you please edit the message above with some context, where did those graphs come from, if they're from running code point to the relevant git commit for versioning (and, also, please always upload a graph with an x axis / y axis label & units))

Thanks! Added some context to the message. Let me know if there are any other details that I'm missing.

**Comment by rahulgovind** [comment]
#160 and #176 cover this issue and we have an interface to both an FFT-based interpolate (`honeybadgermpc.polynomial.fnt_decode_step1` and `honeybadgermpc.polynomial.fnt_decode_step2`) and to Lagrange interpolation (`interpolate` in the `Polynomial class`).

The corresponding NTL-accelerated functions are `honeybadgermpc.ntl.helpers.fft_interpolate` and `honeybadgermpc.ntl.helpers.interpolate`. 

The NTL version also has an interpolate function based on Vandermonde matrices `honeybadgermpc.ntl.helpers.batch_vandermonde_interpolate` which should be used if a batch of polynomials need to be interpolated. Please look at the previous [comment](https://github.com/initc3/HoneyBadgerMPC/issues/152#issuecomment-462074871) for the corresponding speedups. Note that the benchmarks were done for a relatively large batch size (4096) and you should take this into account while choosing which interpolation function you should use.

**Comment by smkuls** [comment]
Closing this for now.
