### ISSUE TITLE
Port tests for reliable broadcast from HoneyBadgerBFT

### ISSUE THREAD

**Issue by smkuls** [initc3/HoneyBadgerMPC#195]
Although we ported [`reliablebroadcast.py`](https://github.com/initc3/HoneyBadgerBFT-Python/blob/dev/honeybadgerbft/core/reliablebroadcast.py) from HoneyBadgerBFT, the corresponding [tests](https://github.com/initc3/HoneyBadgerBFT-Python/blob/dev/test/test_rbc.py) were not ported.

**Comment by amiller** [comment]
I'll close this as low priority, as we have tests for AVID and commonsubset that already address it
