### ISSUE TITLE
Add tests for betterpairing.py

### ISSUE THREAD

**Issue by smkuls** [initc3/HoneyBadgerMPC#196]
Currently there are no tests for `betterpairing.py`. Given the extensive size of the wrapper we should write tests for the same.

**Comment by amiller** [comment]
As a starting point, we could make python versions of some of the relevant tests shown here: https://github.com/initc3/HoneyBadgerMPC/blob/dev/pairing/src/tests/curve.rs

**Comment by amiller** [comment]
Closed with #304
