### ISSUE TITLE
`Event loop is closed` errors in `test_batch_reconstruction.py`

### ISSUE THREAD

**Issue by smkuls** [initc3/HoneyBadgerMPC#211]
There are a large number of `Event loop is closed` errors when you run `test_batch_reconstruction.py`. This is most likely because some the tests are not cleaning up by cancelling their running tasks.

**Comment by Drake-Eidukas** [comment]
We get get this in test_binaryagreement as well.
We can utilize the approach taken in #329  to fix this as well. Perhaps this could be something we tie into pytest through something like [this](https://stackoverflow.com/questions/22627659/run-code-before-and-after-each-test-in-py-test) to ensure this never happens

**Comment by Drake-Eidukas** [comment]
Perhaps that would be a poor idea, as not being able to cancel the tasks indicates poor design and this would mask that... but boy are these warnings annoying.

Update: does not work to do that with an autouse fixture.

**Comment by amiller** [comment]
This was fixed in #330
