### ISSUE TITLE
Add type hints to codebase

### ISSUE THREAD

**Issue by Drake-Eidukas** [initc3/HoneyBadgerMPC#223]
Currently, more or less the entire codebase is written without [type hints](https://docs.python.org/3/library/typing.html), and this can cause some pain points especially with methods that require a specific type to correctly execute. It would be great if we could integrate these hints in our codebase.

- Users of our code who choose to also use type hints / `mypy` would have more ease of use
- We can use this while coding / debugging, as well as benefit from extra documentation.

**Comment by amiller** [comment]
Type hints are now used fairly extensively with #259
