### ISSUE TITLE
Implement jubjub elliptic curve MPC programs

### ISSUE THREAD

**Issue by amiller** [initc3/HoneyBadgerMPC#23]
We will need sample applications of doing elliptic curve operations in jubjub. The examples could be written right now given the interface in passive.py. It should also run the same way given active.py when that is available. We should plan to make one that uses the batch interface as well.
- [x] point addition and doubling operations
- [x] scalar multiplication
- [ ] diffie hellman key exchange in MPC

**Comment by amiller** [comment]
Hanyun's existing repository on jubjub has python examples of elliptic curve operations 
 for jubjub built directly on finite fields https://github.com/hanyunxu/jubjub_python
 So this issue is for implementing it as an MPC program

**Comment by amiller** [comment]
The code for this is clearly nearly ready, but needs to be turned into a PR and merged.
- [x] rebase to dev
- [x] add tests
- [x] documentation
- [x] integration with #25 for decrypt-to-secret-shares as an alternative to hbAVSS for client-efficient input

**Comment by Drake-Eidukas** [comment]
For the workflow on this, which one of these (or neither) would be best here?
1. One pull request
  - Do this all in my fork, and when the branch is in a final state (rebased to dev, tests and docs added), push to the main jubjub branch and pull request
2. Multiple pull requests
  - Tackle each of those points in a separate PRs to jubjub from my fork and then finally PR jubjub back into dev, and then integrate with #25

**Comment by amiller** [comment]
Let's do one PR for each of these since it will be altogether one fairly small self contained patch.
This documentation is hopefully consistent with that: https://github.com/initc3/HoneyBadgerMPC/blob/dev/docs/development/contributing.rst

**Comment by Drake-Eidukas** [comment]
Also, just for sanity checking, is there a jubjub branch on the repo and I just don't have access to it, or are the docs just outdated on that?

**Comment by amiller** [comment]
docs are outdated... actually we ended up with too many cluttered branches on the main repo so we really only want to add a branch here when it's likely to be merged soon

**Comment by Drake-Eidukas** [comment]
Alright, so making sure I'm on the same page, is the intention to move what's in hanyun's repo into the apps directory on the dev branch once those steps have been performed?

**Comment by amiller** [comment]
@hanyunxu  can you advise where is the most recent jubjub code? Is it this?  https://github.com/hanyunxu/HoneyBadgerMPC/blob/comparison/honeybadgermpc/jubjub.py (that appears not to be an MPC program yet)

**Comment by amiller** [comment]
This is in progress with #233
