### ISSUE TITLE
use `__bool__` instead of `__nonzero__`

### ISSUE THREAD

**Issue by amiller** [initc3/HoneyBadgerMPC#230]
field.py needs to be fixed:
https://github.com/initc3/HoneyBadgerMPC/blob/143a43b37016dc4c0b39d94cb991d907a898caaa/honeybadgermpc/field.py#L348
__nonzero__ was deprecated in python2 and in python3 we need to use __bool__ instead
https://portingguide.readthedocs.io/en/latest/core-obj-misc.html#customizing-truthiness-bool

**Comment by Drake-Eidukas** [comment]
Resolved by #232
