### ISSUE TITLE
Improve Travis Build Times

### ISSUE THREAD

**Issue by Drake-Eidukas** [initc3/HoneyBadgerMPC#239]
We should be able to get some quick improvements if we take @smkuls's approach of having a base docker image with dependencies installed, and then basing our travis builds off of that.

Currently, our builds take around 11-12 minutes to run (22-24 minute total time).

**Comment by Drake-Eidukas** [comment]
Currently, builds are down to 8 minutes including testing time. For docs and flake8, we see 2 minutes and 1 minute respectively.

**Comment by Drake-Eidukas** [comment]
#310 Should bring this down to the actual minimal time to build on travis.

**Comment by amiller** [comment]
Closing, just refer to #310 for now
