### ISSUE TITLE
tests hang when changing jubjub to n=3

### ISSUE THREAD

**Issue by amiller** [initc3/HoneyBadgerMPC#264]
I think @Drake-Eidukas is already looking into this, creating an issue just to keep track of it:
- https://github.com/initc3/HoneyBadgerMPC/tree/n4-error-mask
- https://github.com/initc3/HoneyBadgerMPC/pull/262
As far as I can tell, the problem is suppressed by changing the tests in `tests/progs/test_jubjub.py` from `n=3` to `n=4`.  Both of the erroring branches above are with `n=3`. But there's no good reason why this should be the case. What could be going wrong?

**Comment by Drake-Eidukas** [comment]
So, when I was initially working with jubjub, @smkuls mentioned that these tests are way more stable / aren't getting stuck when `n, t = 4, 1` (`n = 3t + 1`), because it expects more points which it's not getting.

I've yet to figure this out but I'm going to look into it more now

**Comment by Drake-Eidukas** [comment]
Do you think this has to do with the fact that the `Equality` mixin for shares utilizes `ShareArray`, and when using share arrays, it calls upon `batch_reconstruct` for opening? According to the docs, it needs that `n >= 3t + 1`. Not sure if this would cause this behaviour with hanging, but it's the best I came up with. Jubjub is the only user of `Equality` I know of.

**Comment by amiller** [comment]
I'm closing this because I can no longer reproduce it. With the current dev branch d8a9c4a even setting this to n=3 the tests all pass
