### ISSUE TITLE
Recommended reading for getting involved? 

### ISSUE THREAD

**Issue by utkarsh5k** [initc3/HoneyBadgerMPC#344]
I'd love to get involved with this project, but I feel like I don't have enough theoretical background on secure MPC. Are there any recommended papers to read? 

Or alternatively, is it advisable to pick an issue and dive in the code?

**Comment by omershlo** [comment]
Hi @utkarsh5k. 
You are welcome to check out project [white-city](https://github.com/KZen-networks/white-city) where we (a team of cryptographers and dist-sys researchers) are building a very similar project from scratch. You can try to pick an issue or talk to me and we will find some easy way to help you get started. There is a [telegram group](https://t.me/kzen_research) for discussing research in threshold cryptography on all levels: I think its a good place to find resources on theoretical background, practical  tools and MPC open source projects.

**Comment by amiller** [comment]
Hi @utkarsh5k thanks for your interest! 
- This paper gives a self-contained explanation of the protocols used in this repository: https://github.com/initc3/HoneyBadgerMPC/blob/paper/docs/HoneyBadgerMPC.pdf
- The background from this tutorial is also very good https://securecomputation.org/ (3.3 BGW protocol
and 3.4 MPC From Preprocessed Multiplication Triples are the most relevant background for hbMPC)
- To get started with the code I would recommend starting by following the instructions in the tutorial: 
https://github.com/initc3/HoneyBadgerMPC/tree/dev/apps/tutorial
