### ISSUE TITLE
Document development processes

### ISSUE THREAD

**Issue by sbellem** [initc3/HoneyBadgerMPC#36]
The goal of this issue is to document (in one place) general guidelines and development tips to contribute to the HoneyBadgerMPC project: 

As a start, the following items could be documented:

**to do first**:
- [x] Add `CONTRIBUTING.md` file. See https://help.github.com/articles/setting-up-your-project-for-healthy-contributions/
- [x] Document setting up a virtual environment, and the development workflow (running tests, cleaning up, etc).
- [x] Choose and document a style guide for the code (e.g.: PEP 8, etc).

---
- [ ] Working with git and github, making pull requests, reviewing code, opening issues, etc.
- [x] Explain the Travis CI checks that are in place (tests, flake8, docs), and give a brief overview of how they may be extended (e.g. adding a build for Ethereum, for different Python versions, etc). 
- [x] Development environments tips & tricks (e.g.: bash completion, using ipython, style checkers)
- [x] Running the tests, troubleshooting, etc.
- [x] Documenting the code, generating the documentation, and viewing it.
- [x] Coding conventions.
---

### Useful resources for documenting a Python project
https://docs.python-guide.org/writing/documentation/

In particular, https://docs.python-guide.org/writing/documentation/#project-publication, suggests the following:

> Depending on the project, your documentation might include some or all of the following components:
>
> * An **introduction** should show a very short overview of what can be done with the product, using one or two extremely simplified use cases. This is the thirty-second pitch for your project.
> * A **tutorial** should show some primary use cases in more detail. The reader will follow a step-by-step procedure to set-up a working prototype.
> * An **API reference** is typically generated from the code (see [docstrings](https://docs.python-guide.org/writing/documentation/#docstring-ref)). It will list all publicly available interfaces, parameters, and return values.
> * **Developer documentation** is intended for potential contributors. This can include code convention and general design strategy of the project.

**More ...**
* https://www.heavybit.com/wp-content/uploads/2016/04/jacob-kaplan-moss-how-great-documentation-drives-developer-adoption.pdf
* https://www.heavybit.com/library/video/how-great-documentation-drives-developer-adoption/
* https://jacobian.org/writing/great-documentation/

**Comment by sbellem** [comment]
- [ ] using a `.global_gitignore` file: https://help.github.com/articles/ignoring-files/#create-a-global-gitignore

**Comment by amiller** [comment]
Dropping this as unfocused. We need to do a documentation cleanup by the end of this semester
