### ISSUE TITLE
Fix travis failures due to encrypted vars not available on PRs

### ISSUE THREAD

**Issue by amiller** [initc3/HoneyBadgerMPC#362]
This looks like it may have been a security feature added recently -
https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
basically, our current build and travis system relies on building images and then pushing them to dockerhub using `$DOCKER_USER` and `$DOCKER_PASSWORD` which are encrypted variables with push access to a docker user within the `dsluiuc` organization. However, since pull requests can come from anywhere really, travis makes sure that these encrypted variables cannot actually be accessed from PRs from contributor repositories.

We should fix this so that at least for commits that do NOT require a change to the docker image, we can build the PRs and avoid that. The travis security guide above suggests a line like: 
```yaml
script:
   - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi'
   - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi'
```
to condition the build behavior on whether it's a PR or not.

For PRs that do modify the image, we may just need to update our workflow so those are only made from the main repo

**Comment by sanket1729** [comment]
Adressed in #371 and #373
