### ISSUE TITLE
Filed run docker-compose run honeybadgermpc

### ISSUE THREAD

**Issue by MuleiOnline** [initc3/HoneyBadgerMPC#436]
when I run `docker-compose run honeybadgermpc`(**Run the tests step**) in the tutorial in the link: 
https://github.com/initc3/HoneyBadgerMPC/blob/dev/docs/development/getting-started.rst#managing-your-development-environment-with-docker-compose
It run at first and will Stuck in the last one or two downloading items. The output:
`alive@ubuntu:~/git-code/HoneyBadgerMPC$ docker-compose run honeybadgermpc
Building honeybadgermpc
Step 1/32 : ARG HBMPC_DEPS_DIGEST="46902d869ea881d7b00b72ff6accf2558a5e15849da5fa5cc722b4ff82a507f8"
Step 2/32 : FROM initc3/honeybadgermpc-deps@sha256:$HBMPC_DEPS_DIGEST AS build-compute-power-sums
sha256:46902d869ea881d7b00b72ff6accf2558a5e15849da5fa5cc722b4ff82a507f8: Pulling from initc3/honeybadgermpc-deps
000eee12ec04: Pull complete
ddc2d83f8229: Pull complete
735b0bee82a3: Pull complete
8c69dcedfc84: Pull complete
495e1cccc7f9: Pull complete
0603ba404131: Downloading [=================================================> ]  90.23MB/90.67MBwnloading [============================================>      ]  3.959MB/4.477MBwnload complete
ce359e408ca1: Download complete
0774965e54e6: Download complete
f7812e9e01c3: Download complete
1677f42f9249: Download complete
649704f164b1: Download complete
3078c9cf50ce: Download complete
45185f43a120: Download complete
24b54f3a9553: Download complete
2bb3a7ea7463: Download complete
003b1fb3ed82: Download complete
6ae7910fef24: Download complete
65b6af5c990c: Download complete
^[.455MB/4.644MB`

I am a new researcher, maybe the question is too simple, but it bother me a lot. Thanks for answer!

**Comment by sbellem** [comment]
Hi @MaLeiOnline, do you still have the problem?
