### ISSUE TITLE
Using dataflow in futures like in Viff

### ISSUE THREAD

**Issue by amiller** [initc3/HoneyBadgerMPC#44]
In Viff the Share objects are subclasses of Future. The operators + * etc. are defined so that if the value of the operands are not available yet, then instead there is a callback added so that when the operands are ready, the computation takes place and the result is set.

This feature makes it easy to write dataflow expressions, that get processed layer by layer, reducing the number of sequential round trips. Without this we have to do it more verbosely.

Consider this fragment for opening `xy` by consuming beaver triple `a`,`b`,`ab`. Because of the awaiting, it proceeds sequentially   
```
    D = await (x - a).open()
    E = await (y - b).open()
    return await (D*b + E*a + ab + D*E).open()
```
We could instead reduce this to just two rounds by explicitly using `gather`:
```
    D,E = await gather((x - a).open(), (y - b).open())
    return await (D*b + E*a + ab + D*E).open()
```

To do something similar to Viff so it's more implicit, we could have a new class:
```
class FieldFuture(Future):
   def __add__(self, other):
        res = FieldFuture()
        if not isWaitable(other):
            other = Future(other)
        gather(self, other).add_done_callback(lambda (a,b): res.set_result(a + b))
        return res
```
compare with https://github.com/amiller/viff/blob/master/viff/passive.py#L133

Then assuming `.open()` returns a FieldFuture, we could use it directly in expressions and get the pipelining/parallel behavior we'd expect.
```
    D = (x - a).open()
    E = (y - b).open()
    return (D*b + E*a + ab + D*E).open()
```

I'm not sure what all the downsides of this are. Here a few details to compare with Viff: 
- When looking at a piece of untyped code, it may be hard to tell if the operations are happening over Shares or FutureShares.
- Viff has every Share be a future by default, so there is no explicit difference of layers between them. 
- There is also not a distinction made between a Share (every party holds a different underlying value) and a field element (every party has the same value). Hence it could make sense to have FieldFuture and ShareFuture be separate objects.

**Comment by smkuls** [comment]
If we introduce `ShareFuture`, then what are the cases wherein we will need just the `Share` object? Won't all `Shares` need to be opened and thus will be of type `ShareFuture` by default?

In case of `Field` values, when are we going to open `Field` elements? If we were to open a `Field` element, won't it be a `Share`?

Although, I agree that introducing callbacks will allows us to write cleaner code which won't be merely sequential.

**Comment by amiller** [comment]
In a lot of case we'll start out with some `Share`s but then make linear combinations of them and just open those.

In this codebase, if you open a `Share`, you get a `Field` in general. You can't further open a `Field`.
So the same with the `ShareFuture` and `FieldFuture` objects. `ShareFuture` and `Share` when opened both give you a `FieldFuture`.  
`Share * Share` beaver multiplication would give you a `ShareFuture`.

**Comment by smkuls** [comment]
These semantics seem a little confusing/complicated to me.

- One `Future` (`ShareFuture`) has an open, the other - `FieldFuture` doesn't have an open. 
- We do start with `Share`s but in most cases if we are going to make linear combinations of them then why introduce another type to just deal with that? In fact, what if we just want to open the `Share` that we start with initially (which is a legal operation)? 

Do we really need a separate type?

1. Like you said, when reading the code one anyway can't figure out if it is a `ShareFuture` or `Share` object.
2. What are the downsides of adding this callback in the existing `Share` object? Consider, when you `open` a `Share` you get a `Field` object.

**Comment by amiller** [comment]
> One Future (ShareFuture) has an open, the other - FieldFuture doesn't have an open.
I think this is actually the right distinction to make. Having an `.open()` method or not is not related to being a `Future` or not. A share object is not the promise of a future value.

I don't understand the suggestion about 2.

**Comment by amiller** [comment]
Summary of the type relationships and operators:
```
await FieldFuture -> Field
await ShareFuture -> Share
Share + Share -> Share
Share * Share -> ShareFuture
ShareFuture + ShareFuture -> ShareFuture
ShareFuture * ShareFuture -> ShareFuture
Share.open() -> FieldFuture
ShareFuture.open() -> FieldFuture
```
Also in general Future dominates, so for anything else `X op Y -> Z` implies `X op YFuture -> ZFuture`
```
ShareFuture + Share -> ShareFuture
Field * FieldFuture -> FieldFuture
.... etc. ```
