### ISSUE TITLE
What is the explicit MPC algorithm of HoneyBadgerMPC

### ISSUE THREAD

**Issue by Federico2014** [initc3/HoneyBadgerMPC#454]
Can anyone provide me the paper link to describe the MPC algorithms details used in HoneyBadgerMPC. Thank you very much.

**Comment by matthiasgeihs** [comment]
[HoneyBadgerMPC and AsynchroMix: Practical Asynchronous MPC and its Application to Anonymous Communication](https://par.nsf.gov/servlets/purl/10130435)
