### ISSUE TITLE
port (viff) `field.py` to Python 3

### ISSUE THREAD

**Issue by sbellem** [initc3/HoneyBadgerMPC#5]
see https://github.com/initc3/HoneyBadgerMPC/blob/dev/field.py#L303-L309

From the Python docs (https://docs.python.org/3.8/whatsnew/3.0.html#ordering-comparisons):

> The `cmp()` function should be treated as gone, and the `__cmp__()` special method is no longer supported. Use `__lt__()` for sorting, `__eq__()` with `__hash__()`, and other rich comparisons as needed. (If you really need the `cmp()` functionality, you could use the expression `(a > b) - (a < b)` as the equivalent for `cmp(a, b)`.)

### Prerequisites
Before proceeding with the required modifications, it is probably a good idea to increase the [code coverage on this module](https://codecov.io/gh/initc3/HoneyBadgerMPC/src/dev/honeybadgermpc/field.py) though, and to use the relevant tests from `viff`.

**Comment by amiller** [comment]
Looks closed by #3

**Comment by sbellem** [comment]
Re-opening, as it was not included in #3 in the end.

**Comment by smkuls** [comment]
@sbellem I am closing this since this has been dormant for a few months now and we have an existing `field.py` which seems to have most of the things that we need for now.
