### ISSUE TITLE
Add `exceptions.py` module for custom exceptions

### ISSUE THREAD

**Issue by sbellem** [initc3/HoneyBadgerMPC#53]
See https://github.com/initc3/HoneyBadgerBFT-Python/blob/dev/honeybadgerbft/exceptions.py for an example.

### Resources
https://dbader.org/blog/python-custom-exceptions
https://www.codementor.io/sheena/how-to-write-python-custom-exceptions-du107ufv9

**Comment by smkuls** [comment]
This has been added.
