### ISSUE TITLE
Implement "naive" hbmpc system chaincode

### ISSUE THREAD

**Issue by sbellem** [initc3/HoneyBadgerMPC#61]
Initial reference at https://github.com/sbellem/fabric/blob/hyperbadgermpc/HBMPC-INTEGRATION.md#add-new-system-chaincode-in-peer.

For this issue, we just want to have HBMPC properly hooked up into the system chaincode machinery. That is:

- [x] add a new system chaincode, e.g.: `hbmpcscc` under `core/scc`
- [x] `hbmpcscc` needs to be instantiated and registered under `peer/node/start.go`
- [ ] add a unit test for `hbmpcscc`, just so that future iterations can re-use the unit test and refine it as needed
- [ ] add an end-to-end example under `examples` -- look at the other `e2e` examples for inspiration

What HBMPC does at this point can be a "dummy" action. We just wish to verify that everything is accessible and integrated within the peer & chaincode mechanism.

- [ ] simple communication test using `netcat` (idea by @amiller) (also see https://hub.docker.com/r/gophernet/netcat/)

**Comment by amiller** [comment]
Avesta noted that his team has some progress on between-endorser communication as well. If possible to link to, would be great to establish the correspondence here

**Comment by amiller** [comment]
We have already implemented a solution to this, @hybridNeo can you update with info in #24
