### ISSUE TITLE
destroy all, rejoice and use yeasy/docker-hyperledger-fabric

### ISSUE THREAD

**Issue by sbellem** [initc3/HoneyBadgerMPC#62]
Like a gift from the sky: https://github.com/yeasy/docker-hyperledger-fabric

So let's use this for the dev environment for the integration. That is, revisit work done in #52 and use this docker image.

We should be able to easily add HBMPC to it. This will also hopefully help with running the tests on travis.

- [ ] reach same status as of now as per https://github.com/sbellem/fabric/blob/hyperbadgermpc/HBMPC-INTEGRATION.md#dev-notes-integration-with-honeybadgermpc
- [ ] run the integration tests withing a container
- [ ] run tests on travis

**Comment by amiller** [comment]
Closing as we are deciding to continue using our own for now
