### ISSUE TITLE
test package meta-data and reST with `python setup.py check` 

### ISSUE THREAD

**Issue by sbellem** [initc3/HoneyBadgerMPC#63]
This is some kind of quality control check that can be performed on the package. Eventually, when we start making releases on PyPI, this can prevent problems such as the project description not being rendered properly, or some meta-data missing.

Some projects such as [`cryptography`](https://github.com/pyca/cryptography/blob/master/tox.ini#L49) and [`astropy`](https://github.com/astropy/astropy/issues/5495) use it.

Running the check currently returns errors:

```bash
$ python setup.py check --restructuredtext --strict
running check
warning: check: missing required meta-data: url

warning: check: missing meta-data: either (author and author_email) or (maintainer and maintainer_email) must be supplied

warning: check: Inline emphasis start-string without end-string. (line 141)

warning: check: Inline emphasis start-string without end-string. (line 141)

error: Please correct your package.
```

We can the check to the docs build job on travis just like [`cryptography`](https://github.com/pyca/cryptography/blob/master/tox.ini#L49) does.

Some references:

* https://docs.python.org/3.7/distutils/apiref.html#module-distutils.command.check
* https://stackoverflow.com/a/30332432/2769475

**Comment by amiller** [comment]
Closing this. Possibly @Drake-Eidukas wants to look into it
