### ISSUE TITLE
documentation quality checks

### ISSUE THREAD

**Issue by sbellem** [initc3/HoneyBadgerMPC#64]
- [x] **style check**: use [doc8](https://github.com/openstack/doc8) 
- [x] ~~**spelling check**: use [sphinxcontrib-spelling](https://sphinxcontrib-spelling.readthedocs.io/en/latest/index.html)~~ -- dependency [pyenchant](https://github.com/rfk/pyenchant) is no longer maintained 
- [x] ~~maybe: https://github.com/myint/rstcheck~~ -- does not work with latest Sphinx (https://github.com/myint/rstcheck/issues/50)

**Comment by amiller** [comment]
Closed as looks complete
