### ISSUE TITLE
gmpy is no longer being maintained: use gmpy2?

### ISSUE THREAD

**Issue by sbellem** [initc3/HoneyBadgerMPC#70]
Just wondering if there is a reason for using [gmpy](https://pypi.org/project/gmpy/) instead of [gmpy2](https://pypi.org/project/gmpy2/).

From https://pypi.org/project/gmpy/:

> gmpy 1.17 is the final release of the 1.x series. No further updates are planned. All further development is occurring in the 2.x series, also known as gmpy2. Please see https://pypi.python.org/pypi/gmpy2/ for the latest 2.x releases.

- [x] Just replace `gmpy` with `gmpy2` and see if the tests still pass.

**Comment by amiller** [comment]
I think no reason, this is probably brought over from Viff.

**Comment by sbellem** [comment]
Resolved via #73.
