### ISSUE TITLE
Add a license to the project

### ISSUE THREAD

**Issue by sbellem** [initc3/HoneyBadgerMPC#84]
Once the license is chosen we can also add it to `setup.py`, in the classifiers section. See https://pypi.org/classifiers/ for a list of licenses and how to include them in the `setup.py`. If the license being used is not in there (e.g.: CRAPL) we can use `License :: Other/Proprietary License`.

We can also add a badge to the readme file. See https://shields.io/#/examples/license for examples on how to do so.

**Comment by amiller** [comment]
For later
