### ISSUE TITLE
Publish docs to github pages instead of readthedocs

### ISSUE THREAD

**Issue by sbellem** [initc3/HoneyBadgerMPC#85]
Because HoneyBadgerMPC depends on some C libraries such as `gmp` using Read the docs is somewhat cumbersome as it does not have `gmp` installed and it is not possible to install it ourselves. Instead the following workaround is proposed: https://docs.readthedocs.io/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules. Although this may work it is not so practical and it is also not clear (to me at least) if this may impact the documentation generation, more particularly the parts generated with `autodoc`. At the moment of this writing the docs can build properly using the above workaround but the parts involving `autodoc` (docstrings) are not generated and it is not clear why.

Since we are already building the docs on travis as part of the CI phase, we could deploy them to github pages from there.

This approach has the major advantage that we can use docker to have all the dependencies we need to build the docs, install the project etc. 

Moreover, if the docs are properly generated in one's own local development environment, based on docker, the chances that it also builds properly on travis are quite high since a very similar docker image and build process is used.

Documentation on how to do so can be found at https://docs.travis-ci.com/user/deployment/pages/

The following may also be of some interest: https://gist.github.com/domenic/ec8b0fc8ab45f39403dd

**Comment by sbellem** [comment]
Relevant: https://github.com/travis-ci/dpl/issues/694

**Comment by amiller** [comment]
Close for now
